name: test-parabank-soatest-linux

on: 
 # push:
    #branches: [ main ]
    # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
jobs:
  test-soatest:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: My custom action
      uses: lyao-parasoft/run-soatest-action@master
      with:
        installDir: /home/devtest/soa/parasoft/soatest_virtualize/2023.2
        soatestWorkspace: ${{ github.workspace }}/soatest
        testConfig: builtin://Demo Configuration
        resource: TestAssets
        settings: soatest/localsettings.properties
        report: soatest/reports/report.xml
        reportFormat: xml
        #environment: 
        convertReportToXUnit: true
        additionalParams:
         -include Smoke.tst
        
