name: test-parabank-soatest-System-test

on: 
 # push:
    #branches: [ main ]
    # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
jobs:
  test-soatest:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run-soatest-action
      uses: lyao-parasoft/run-soatest-action@master
      with:
        installDir: C:/Program Files\\Parasoft/SOAtest&Virtualize/2023.2
        soatestWorkspace: ${{ github.workspace }}/soatest
        testConfig: builtin://Demo Configuration
        resource: TestAssets
        settings: soatest/localsettings.properties
        report: soatest/report-parabank&soatest-action
        reportFormat: xml
        environment: ../../test-env.env
        convertReportToXUnit: true
        # javaRootPath: C:/Program Files/Java/jdk-11
        additionalParams:
         -include PB-ParabankServices-v3.tst
        
