name: test-parabank-soatest-System-test

on: 
 # push:
    #branches: [ main ]
    # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
jobs:
  test-soatest:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run-soatest-action
      uses: lyao-parasoft/run-soatest-action@master
      with:
        installDir: C:\Program Files\Parasoft\SOAtest&Virtualize\2023.2
        soatestWorkspace:  ${{ github.workspace }}/soatest
        testConfig: builtin://Demo Configuration
        resource: TestAssets/PB-ParabankServices-v3.tst
        settings: soatest/localsettings.properties
        report: soatest/reports
        reportFormat: xml
        environment: ../../test-env
        convertReportToXUnit: TRUE
        additionalParams:
         -include PB-ParabankServices-v3.tst
 
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      with:
       files: |
        soatest\reports\*-xunit.xml

        
