name: test-parabank-soatest-System-test

on: 
 # push:
    #branches: [ main ]
    # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
jobs:
  test-soatest:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run-soatest-action
      uses: lyao-parasoft/run-soatest-action@master
      with:
        installDir: C:/Program Files\\Parasoft/SOAtest&Virtualize/2023.2
        soatestWorkspace: D:\Github-runner\parabank-soatest-runner\_work\parabank-soatest\parabank-soatest\soa test
        #${{ github.workspace }}/soa test/D:\Github-runner\parabank-soatest-runner\_work
        testConfig: builtin://Demo Configuration
        resource: " "
        settings: soatest/localsettings.properties
        #report: ' '
        reportFormat: " "
        environment: ../../test-env.env
        convertReportToXUnit: False
        # javaRootPath: C:/Program Files/Java/jdk-11
        additionalParams:
         -include PB-ParabankServices-v3.tst
        
