name: test-parabank-soatest-03/21

on: [push]

jobs:
  test-soatest:
    runs-on: self-hosted
    steps:
    - name: cd soatest directory
      run: cd ./sotest
    - name: My custom action
      uses: lyao-parasoft/run-soatest-action@test-luffy
